### ISSUE TITLE
"failed to fetch any source profiles"

### ISSUE THREAD

**Issue by bboreham** [conprof/conprof#36] opened 2019-11-28 18:09 UTC
Sometimes I click on a blob in the timeline and it opens up a page saying "failed to fetch any source profiles".

I have seen three different log messages that all seem to be associated with (different variants of?) this issue:
```
2019/11/28 18:03:48 : decompressing profile: gzip: invalid header
2019/11/28 18:04:46 : decompressing profile: unexpected EOF
2019/11/28 18:07:49 : parsing profile: unrecognized profile format
```

I guess it's always possible that the scrape fails, but it would be better if the UI didn't show a blob at that time.

**Comment by brancz** [comment] 2019-12-03 13:04
Yes I've noticed this as well, I haven't fully figured out why this happens, as we do [parse profiles before](https://github.com/conprof/conprof/blob/32be39bee4584a89614bb25f618d53d966b685cc/scrape/scrape.go#L381-L384) appending them. Maybe we need to do run further validations on the profile rather than just parsing it. Maybe an empty profile is a valid one, I'm not sure.

**Comment by brancz** [comment] 2019-12-04 09:05
I just double checked, and honestly I don't understand how those samples get persisted, as parsing the profile should encounter the exact same issue judging by: https://github.com/google/pprof/blob/27840fff0d09770c422884093a210ac5ce453ea6/profile/profile.go#L167-L177

**Comment by josharian** [comment] 2020-11-14 00:24
We hit this as well. I think the stored data is getting corrupted: I've seen a particular profile go from readable (because it rendered nicely) to `"failed to fetch any source profiles"`. A large proportion of our samples right now are failing...

**Comment by brancz** [comment] 2020-11-14 11:50
I believe since the last storage rebase this started happening for data older than 8h, potentially even 2h.

I’m gonna try to build some data integrity tooling to test this over time.

**Comment by inge4pres** [comment] 2020-11-18 16:54
Hey I'm using the `latest` version too and facing this same issue for data just collected: how to debug, is there an option to add verbose logging?
Can you please also point me to a document/part of code that handles the scraping, I am not sure if I need to configure the targest with the HTTP host-port only or if I need to add the `/debug` URI too...
Thanks for this beautiful tool 👍🏼

**Comment by inge4pres** [comment] 2020-11-18 17:11
One more hint on this: when switching to version `master-2020-11-04-ce50636` this log line appears

```
2020/11/18 17:09:35 : decompressing profile: gzip: invalid header
```

**Comment by brancz** [comment] 2020-11-26 14:29
My apologies for taking so long to get back to this. Re-reading your https://github.com/conprof/conprof/issues/36#issuecomment-729810363 @inge4pres , are you saying you are trying to view `trace` type profiles? If so I think this is our mistake, as we don't actually support viewing trace profiles, as we never ended up finishing https://github.com/conprof/conprof/pull/56 / #61 .

I think we should probably disable scraping trace profiles by default until we have this support implemented, to avoid confusing situations like this (if this is the case).

---

Regarding your last comment, do you have a sequence of steps to run to reproduce this? I can't by just running a conprof instance from scratch, however, if I run conprof, collect some data, shut it down, and then start it back up, I can indeed reproduce some `failed to fetch any source profiles` errors. I'll investigate why this is happening.

**Comment by inge4pres** [comment] 2020-11-26 16:15
Hi @brancz the steps you describe are exactly the one needed to reproduce, for some reasons it's like the tsdb files becomes unreadable?

**Comment by brancz** [comment] 2020-11-26 17:07
I have two hunches right now, either the chunks mmap'ed to disk are somehow corrupted, or when WAL replay happens they get corrupted in some way. The later would be better for us as that would mean the storage isn't corrupted, just the way we load them. Once I have a better idea I'll report back here! :) 

Thank you so much for reporting!

**Comment by brancz** [comment] 2020-11-27 14:04
Quick update: It appears I have found part of the problem, there was an unsafe loading of data in the WAL. So the good news is that there is no corruption of the data on disk. Bad news is that for some reason new appends still yield this error, but when restarted those appends can be viewed without issues. I'm continuing to investigate.

**Comment by inge4pres** [comment] 2020-11-27 16:08
If you can give a pointer to a piece of code and/or a test to debug, I'd be happy to fork and see if I can help 😄

**Comment by brancz** [comment] 2020-11-27 16:10
I just opened a PR to fix most problems that I found so far in the tsdb (https://github.com/conprof/db/pull/2), but the later issue is still present though.

**Comment by brancz** [comment] 2020-11-27 18:19
I just wrote an extensive test that seems to indicate that the database is functioning just fine.

**Comment by brancz** [comment] 2020-11-30 17:56
I tried a number of things, and definitely found a couple of small problems, but none of those ended up fixing this symptom. For what it's worth I was finally able to write a test to reproduce this.

**Comment by brancz** [comment] 2020-11-30 18:47
I think I found the last "failed to fetch" errors with: https://github.com/conprof/conprof/pull/112.

There is still a remaining problem though, which is after a restart, previous series don't seem to be continued for some reason. At least now we're in a state where all data is viewable and queryable though (with more tests to prevent this from happening again in the future)! :tada:

**Comment by brancz** [comment] 2020-12-01 15:16
I finally managed to find that last bug, and all new e2e tests are passing with this patch: https://github.com/conprof/conprof/pull/113

Thank you so much everyone for bearing with me!

**Comment by brancz** [comment] 2020-12-01 15:30
With #112 and #113 merged I think we can close this. Thank you everyone for reporting, and please open new issues if you find anything else or if you think this isn't resolved with the latest versions!

**Closed by brancz** 2020-12-01 15:30 UTC

**Comment by inge4pres** [comment] 2020-12-01 15:42
Thanks! Will test asap and send some feedback
