### ISSUE TITLE
race detector failures

### ISSUE THREAD

**Issue by josharian** [conprof/conprof#100] opened 2020-11-14 00:29 UTC
I started up conprof built with -race and almost immediately got complaints:

```
or/github.com/conprof/db/tsdb/chunkenc/byte.go:172 +0x48f
  github.com/conprof/db/tsdb.(*memSeries).append()
      /Users/josh/x/conprof/vendor/github.com/conprof/db/tsdb/head.go:2130 +0x198
  github.com/conprof/db/tsdb.(*Head).processWALSamples()
      /Users/josh/x/conprof/vendor/github.com/conprof/db/tsdb/head.go:372 +0x3fd
  github.com/conprof/db/tsdb.(*Head).loadWAL.func5()
      /Users/josh/x/conprof/vendor/github.com/conprof/db/tsdb/head.go:466 +0x66

Previous write at 0x00c000f62010 by goroutine 55:
  runtime.slicecopy()
      /Users/josh/go/1.15/src/runtime/slice.go:246 +0x0
  github.com/conprof/db/tsdb/wal.(*Reader).next()
      /Users/josh/x/conprof/vendor/github.com/conprof/db/tsdb/wal/reader.go:134 +0xe04
  github.com/conprof/db/tsdb/wal.(*Reader).Next()
      /Users/josh/x/conprof/vendor/github.com/conprof/db/tsdb/wal/reader.go:45 +0x44
  github.com/conprof/db/tsdb.(*Head).loadWAL.func6()
      /Users/josh/x/conprof/vendor/github.com/conprof/db/tsdb/head.go:474 +0x9d

Goroutine 34 (running) created at:
  github.com/conprof/db/tsdb.(*Head).loadWAL()
      /Users/josh/x/conprof/vendor/github.com/conprof/db/tsdb/head.go:465 +0x549
  github.com/conprof/db/tsdb.(*Head).Init()
      /Users/josh/x/conprof/vendor/github.com/conprof/db/tsdb/head.go:713 +0xdf0
  github.com/conprof/db/tsdb.open()
      /Users/josh/x/conprof/vendor/github.com/conprof/db/tsdb/db.go:660 +0xb84
  github.com/conprof/db/tsdb.Open()
      /Users/josh/x/conprof/vendor/github.com/conprof/db/tsdb/db.go:530 +0xe4
  main.runAll()
      /Users/josh/x/conprof/all.go:46 +0x20c
  main.registerAll.func1()
      /Users/josh/x/conprof/all.go:41 +0x1d4
  main.main()
      /Users/josh/x/conprof/main.go:131 +0x1f4e

Goroutine 55 (running) created at:
  github.com/conprof/db/tsdb.(*Head).loadWAL()
      /Users/josh/x/conprof/vendor/github.com/conprof/db/tsdb/head.go:472 +0x70d
  github.com/conprof/db/tsdb.(*Head).Init()
      /Users/josh/x/conprof/vendor/github.com/conprof/db/tsdb/head.go:713 +0xdf0
  github.com/conprof/db/tsdb.open()
      /Users/josh/x/conprof/vendor/github.com/conprof/db/tsdb/db.go:660 +0xb84
  github.com/conprof/db/tsdb.Open()
      /Users/josh/x/conprof/vendor/github.com/conprof/db/tsdb/db.go:530 +0xe4
  main.runAll()
      /Users/josh/x/conprof/all.go:46 +0x20c
  main.registerAll.func1()
      /Users/josh/x/conprof/all.go:41 +0x1d4
  main.main()
      /Users/josh/x/conprof/main.go:131 +0x1f4e
==================
==================
WARNING: DATA RACE
Read at 0x00c000f6ff40 by goroutine 34:
  runtime.slicecopy()
      /Users/josh/go/1.15/src/runtime/slice.go:246 +0x0
  github.com/conprof/db/tsdb/chunkenc.(*bytesAppender).Append()
      /Users/josh/x/conprof/vendor/github.com/conprof/db/tsdb/chunkenc/byte.go:172 +0x48f
  github.com/conprof/db/tsdb.(*memSeries).append()
      /Users/josh/x/conprof/vendor/github.com/conprof/db/tsdb/head.go:2130 +0x198
  github.com/conprof/db/tsdb.(*Head).processWALSamples()
      /Users/josh/x/conprof/vendor/github.com/conprof/db/tsdb/head.go:372 +0x3fd
  github.com/conprof/db/tsdb.(*Head).loadWAL.func5()
      /Users/josh/x/conprof/vendor/github.com/conprof/db/tsdb/head.go:466 +0x66

Previous write at 0x00c000f6ff45 by goroutine 55:
  [failed to restore the stack]

Goroutine 34 (running) created at:
  github.com/conprof/db/tsdb.(*Head).loadWAL()
      /Users/josh/x/conprof/vendor/github.com/conprof/db/tsdb/head.go:465 +0x549
  github.com/conprof/db/tsdb.(*Head).Init()
      /Users/josh/x/conprof/vendor/github.com/conprof/db/tsdb/head.go:713 +0xdf0
  github.com/conprof/db/tsdb.open()
      /Users/josh/x/conprof/vendor/github.com/conprof/db/tsdb/db.go:660 +0xb84
  github.com/conprof/db/tsdb.Open()
      /Users/josh/x/conprof/vendor/github.com/conprof/db/tsdb/db.go:530 +0xe4
  main.runAll()
      /Users/josh/x/conprof/all.go:46 +0x20c
  main.registerAll.func1()
      /Users/josh/x/conprof/all.go:41 +0x1d4
  main.main()
      /Users/josh/x/conprof/main.go:131 +0x1f4e

Goroutine 55 (running) created at:
  github.com/conprof/db/tsdb.(*Head).loadWAL()
      /Users/josh/x/conprof/vendor/github.com/conprof/db/tsdb/head.go:472 +0x70d
  github.com/conprof/db/tsdb.(*Head).Init()
      /Users/josh/x/conprof/vendor/github.com/conprof/db/tsdb/head.go:713 +0xdf0
  github.com/conprof/db/tsdb.open()
      /Users/josh/x/conprof/vendor/github.com/conprof/db/tsdb/db.go:660 +0xb84
  github.com/conprof/db/tsdb.Open()
      /Users/josh/x/conprof/vendor/github.com/conprof/db/tsdb/db.go:530 +0xe4
  main.runAll()
      /Users/josh/x/conprof/all.go:46 +0x20c
  main.registerAll.func1()
      /Users/josh/x/conprof/all.go:41 +0x1d4
  main.main()
      /Users/josh/x/conprof/main.go:131 +0x1f4e
==================
```

Maybe a cause of https://github.com/conprof/conprof/issues/36?

**Comment by brancz** [comment] 2020-11-14 11:48
Yeah I’ve noticed this recently as well, it appears to be rather severe, sometimes so bad that discovery doesn’t start this scraping doesn’t start.

**Comment by brancz** [comment] 2020-11-14 11:49
I’m gonna try to have a look at this next week.

**Comment by brancz** [comment] 2020-11-30 13:10
This should be fixed (through: https://github.com/conprof/db/commit/173f6e8862d7e52b4e39d1d6d433e1d24b234e29#diff-b64b52f2cd0b36cf8b064c3bf3630f5ff837d1bde5d780cca16b1dd10b7f82b3R183). Could you double check this? I can't reproduce any obvious races anymore.

Thank you so much for reporting this!

**Comment by brancz** [comment] 2020-12-03 08:42
I've tried for a couple of days now and haven't been able to reproduce any races, I'm gonna go ahead and close this, but please feel free to continue to comment or open a new issue if you should encounter any other race with the latest version!

**Closed by brancz** 2020-12-03 08:42 UTC
